// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPpNJmP2O0bc7qC0JNYFB44lpGDmmVltg',
    appId: '1:462775634583:web:728768d5a2461e762637d2',
    messagingSenderId: '462775634583',
    projectId: 'agi-othm-attendance',
    authDomain: 'agi-othm-attendance.firebaseapp.com',
    storageBucket: 'agi-othm-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuxxUoFVBZv8px041vV1uLGk7bDqpAuXE',
    appId: '1:462775634583:ios:161c3cd16ec858f32637d2',
    messagingSenderId: '462775634583',
    projectId: 'agi-othm-attendance',
    storageBucket: 'agi-othm-attendance.firebasestorage.app',
    iosBundleId: 'com.example.myAppFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuxxUoFVBZv8px041vV1uLGk7bDqpAuXE',
    appId: '1:462775634583:ios:161c3cd16ec858f32637d2',
    messagingSenderId: '462775634583',
    projectId: 'agi-othm-attendance',
    storageBucket: 'agi-othm-attendance.firebasestorage.app',
    iosBundleId: 'com.example.myAppFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPpNJmP2O0bc7qC0JNYFB44lpGDmmVltg',
    appId: '1:462775634583:web:9e36247c0ff6dcd12637d2',
    messagingSenderId: '462775634583',
    projectId: 'agi-othm-attendance',
    authDomain: 'agi-othm-attendance.firebaseapp.com',
    storageBucket: 'agi-othm-attendance.firebasestorage.app',
  );
}
